services:
    fred:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: "./docker/Dockerfile"
        environment:
            FRED_IP: '::'
            FRED_PORT: 80
            FRED_TOKEN: '${FRED_TOKEN}'
            DIALOGFLOW_AUTH: '${DIALOGFLOW_AUTH}'
            FRED_SQL_DB: 'fred'
            FRED_SQL_USER: 'fred'
            FRED_SQL_PASSWORD: 'fred'
            FRED_SQL_HOST: postgres
            FRED_SQL_PORT: 5432
        ports:
            - "80:80"

    postgres:
        image: postgres:14.0-alpine
        environment:
            POSTGRES_PASSWORD: fred
            POSTGRES_USER: fred
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata:z
            - ./docker/exampledb.sql:/docker-entrypoint-initdb.d/exampledb.sql

    pgadmin:
        depends_on:
            - postgres
        image: dpage/pgadmin4:6
        environment:
            PGADMIN_DEFAULT_EMAIL: 'fred@fred.com'
            PGADMIN_DEFAULT_PASSWORD: 'fred'
        ports:
            - "8080:80"

volumes:
    pgdata: