include:
    - docker-compose-deps.yml
services:
    fred:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: "./docker/Dockerfile"
        environment:
            FRED_IP: '::'
            FRED_PORT: 80
            FRED_TOKEN: '${FRED_TOKEN}'
            FRED_SQL_DB: 'fred'
            FRED_SQL_USER: 'fred'
            FRED_SQL_PASSWORD: 'fred'
            FRED_SQL_HOST: postgres
            FRED_SQL_PORT: 5432
        ports:
            - "80:80"